#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]


    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    enable_guicolors = true


    default_indent = 4
    relativenumber = true


    # lint
    enable_neomake = false
    enable_ale = true
    lint_on_the_fly = true


    automatic_update = 0


    autocomplete_method = "coc"


    # file manager
    enable_vimfiler_gitstatus = true


    # statusline
    # Set the statusline separators of statusline, default is "arrow"
    statusline_separator = "arrow"
    # Set the statusline separators of inactive statusline
    statusline_inactive_separator = "bar"
    # Set SpaceVim buffer index type
    buffer_index_type = 4
    # 0: 1 ➛ ➊
    # 1: 1 ➛ ➀
    # 2: 1 ➛ ⓵
    # 3: 1 ➛ ¹
    # 4: 1 ➛ 1
# Enable/Disable show mode on statusline
    enable_statusline_mode = true

    # left sections of statusline
    statusline_left_sections = [
       'winnr',
       # 'major mode',
       'filename',
       # 'fileformat',
       # 'minor mode lighters',
       'version control info',
       'search status'
    ]
    # right sections of statusline
    statusline_right_sections = [
       'cursorpos',
       'percentage',
       # 'input method',
       # 'date',
       # 'time'
    ]
    # custom setting
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "VersionControl"

[[layers]]
name = "git"

[[layers]]
name = "checkers"
show_cursor_error = false

[[layers]]
name = "colorscheme"

[[layers]]
name = "ui"

[[layers]]
name = "debug"

[[layers]]
name = "default"

[[layers]]
name = "sudo"

[[layers]]
name = "lang#java"

[[layers]]
name = "lang#python"

[[layers]]
name = "lang#go"

[[layers]]
name = "lang#javascript"

[[layer]]
name = "lang#c"

[[layers]]
name = "lsp"
filetypes = [
    "python",
    "go",
    "java"
    "javascript"
    "c"
    "cpp"
]
[layers.override_cmd]
    java = [
    "java",
    "-Declipse.application=org.eclipse.jdt.ls.core.id1",
    "-Dosgi.bundles.defaultStartLevel=4",
    "-Declipse.product=org.eclipse.jdt.ls.core.product",
    "-Dlog.protocol=true",
    "-Dlog.level=NONE",
    "-noverify",
    "-Xmx1G",
    "-jar",
    "/home/wxx/.lsp/plugins",
    "-configuration",
    "/home/wxx/.lsp/config_linux",
    "-data",
    "/home/wxx/.cache/javalsp"
    ]

[[layers]]
name = "format"

[[layers]]
name = "tmux"

[[custom_plugins]]
name = "lilydjwg/colorizer"
merged = 0
